### ISSUE TITLE
本地pdf为什么显示不了

### ISSUE THREAD

**Issue by ncepuee** [next-theme/theme-next-pdf#1]
本地的pdf显示不了，为什么？

**Comment by stevenjoezhang** [comment]
可能的原因有很多，你可以把博客上传之后发个链接，我来 debug

**Comment by hizablet** [comment]
> 可能的原因有很多，你可以把博客上传之后发个链接，我来 debug
我是用的localhost:4000查看，没有`hexo d`，上传到GitHub之后，不会显示任何东西

**Comment by hizablet** [comment]
> 可能的原因有很多，你可以把博客上传之后发个链接，我来 debug

这是我做的pdf预览的网站：file.hinohi.com/web/viewer.html?file=AboutReading_professorLuo.pdf
但是不知道Next博客应该怎么弄

**Comment by hizablet** [comment]
> 可能的原因有很多，你可以把博客上传之后发个链接，我来 debug

我搭建网站访问是需要root/web/viewer.html?file=(放在pdfjs的web文件夹下的pdf的名字)

**Comment by stevenjoezhang** [comment]
你需要把pdf文件放到和你的网站相同的域名下，如果一个是`file.hinohi.com`，一个是`hinohi.com`，那么会有跨域的问题，需要设置 CORS headers 才能加载
