### ISSUE TITLE
Fail to render pdf using pdf.js

### ISSUE THREAD

**Issue by v1siuol** [next-theme/theme-next-pdf#3]
Please follow this Issue template to provide relevant information, such as source code repository, website URL and screenshots, which will help us investigate.
请按照此 Issue 模版提供相关信息，例如源码仓库、网站链接和屏幕截图，这将有助于我们进行调查。

## Issue Checklist 

- [X] I am using NexT version 8.0 or later.
- [X] I have already read the [Troubleshooting page of Hexo](https://hexo.io/docs/troubleshooting) and [Troubleshooting page of NexT](https://theme-next.js.org/docs/troubleshooting.html).
- [X] I have already searched for current [issues](https://github.com/next-theme/hexo-theme-next/issues), which does not help me.

***

## Expected behavior 
PDF is rendered correctly.

## Actual behavior 
More precisely, the pdf is rendered. But its height is 0, which results to missing pdf issue.

- Links to demo site with this issue: I will provide a repo that reproduces this issue, feel free to build it locally. 
- Links to repository or source code of the blog: https://github.com/v1siuol/hexo-mwe/tree/next-pdfjs-issue
- Screenshots:
![Snipaste_2021-06-22_01-52-00](https://user-images.githubusercontent.com/18160111/122871046-7915de80-d2fc-11eb-9e6f-edcd57a02a0b.png)

## Steps to reproduce the behavior 
1. Install latest `hexo`, `hexo-theme-next` and `theme-next-pdf`. 
2. **Enforce PDF rendering by pdf.js.** (Add `forcePDFJS : true` right under `height   : element.dataset.height,` in `/themes/next/source/js/third-party/tags/pdf.js`)
3. Add test pdf and Deploy.

Or

```
git clone git@github.com:v1siuol/hexo-mwe.git next-pdfjs-issue
cd next-pdfjs-issue
git checkout next-pdfjs-issue
git submodule update --init --recursive
npm install
hexo server -p 5000
```

### Node.js and NPM Information

```
$ node -v && npm -v
v14.12.0
6.14.13
```

### Package dependencies Information

```
$ npm ls --depth 0
hexo-site@0.0.0 [dump_directory]
├── hexo@5.4.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@4.0.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@2.0.0
└── hexo-theme-landscape@0.0.3
```

### Hexo Configuration

```yml
+ theme: next

skip_render:
+ - "lib/**/*"  # Will output any file and subfolder in `source/lib/` without altering them.
```

### NexT Configuration

```yml
pdf:
+  enable: true
```

## Other Information 
- Windows 
- Chrome 91.0.4472.106

**Comment by v1siuol** [comment]
I inspected the element and found that there is a weird div block added, which might explain this issue.
```
<div class="pdf-container pdfobject-container" data-target="/images/test.pdf" data-height="500px" style="position: relative; overflow: auto;">
  <div style="position: absolute; inset: 0px;">
    <iframe src="/lib/pdf/web/viewer.html?file=%2Fimages%2Ftest.pdf#navpanes=0&amp;toolbar=0&amp;statusbar=0&amp;pagemode=thumbs&amp;view=FitH" class="pdfobject" allow="fullscreen" style="border: none; width: 100%; height: 100%;"></iframe>
  </div>
</div>
```

**Comment by stevenjoezhang** [comment]
Thanks for your feedback, the document is updated in dd63bf6dc5822d8a3bfc644a74e163a07d82a0b9

**Comment by stevenjoezhang** [comment]
`fallbackLink` is enabled by default in PDFObject

https://github.com/pipwerks/PDFObject/blob/master/pdfobject.js#L274
